export const APIS = {
  DASHBOARD: {
    DATA: "/dashboard/dashboard",
  },
  USER: {
    ADD: "/user/add",
    LOGIN: "/user/login",
    FORGETPASSWORD: "/user/forget-password",
    RESETPASSWORD: "/user/reset-password",
    CHANGEPASSWORD: "/user/change-password",
    EDIT: (userId) => `/user/${userId}`,
    VIEW: (userId) => `/user/${userId}`,
    DASHBOARD: "/user/dashboard",
    MANAGERLIST: "/user/get-managers",
    ALLUSER: "/user/get-all-user",
    EMPLOYEELIST: "/user/get-all-employees",
    INVITEDLIST: "/user/get-invited-user",
    DELETE: (employeeId) => `/user/${employeeId}`,
  },
  CLIENT: {
    ADD: "/client/add",
    EDIT: (clientId) => `/client/${clientId}`,
    VIEW: (clientId) => `/client/${clientId}`,
    LIST: "/client/get-clients",
    DELETE: (clientId) => `/client/${clientId}`,
  },
  PROJECT: {
    ADD: "/project/add",
    EDIT: (projectId) => `/project/${projectId}`,
    VIEW: (projectId) => `/project/${projectId}`,
    DELETE: (projectId) => `/project/${projectId}`,
    LIST: "/project/get-projects",
    CLIENTWISEPROJECT: (clientId) => `/project/get-project-name/${clientId}`,
  },
  BANK: {
    ADD: "/bank/add",
    VIEW: (bankId) => `/bank/${bankId}`,
    USERBANK: (userId) => `/bank/user/${userId}`,
    LIST: "/bank/get-banks",
    DELETE: (bankId) => `/bank/${bankId}`,
    EDIT: (bankId) => `/bank/${bankId}`,
  },
  INVOICE: {
    GENERATENUM: "/invoice/generate-invoice-number",
    ADD: "/invoice/add",
    EDIT: "/invoice/edit",
    DELETE: (invoiceId) => `/invoice/${invoiceId}`,
    CHECKINVOICENUMBER: (number) => `/invoice/check-invoice-number/${number}`,
    LIST: "/invoice/invoices",
  },
  COUNTRY: {
    GET: "/country-code",
  },
  CURRENCY: {
    GET: "/currency",
  },
  ADMIN: {
    GET: "/admin/getAdmin",
    EDIT: "/admin/edit",
  },
  TASK: {
    GET: (projectId) => `/task/tasks/${projectId}`,
    ADD: "/task/add",
    EDIT: (taskId) => `/task/${taskId}`,
  },
  SALARY: {
    ADD: "/salary/add",
    GET: (userId) => `/salary/user/${userId}`,
    DELETE: (userId) => `/salary/${userId}`,
    ALL: "/salary",
  },
  LEAVE: {
    ADD: "/leave/apply",
    EDIT: (userId) => `/leave/${userId}`,
    LIST: (userId) => `leave/user/${userId}`,
    APPROVELIST: `leave/approve`,
    ALL: `leave/all`,
    DASHBOARD: "leave/dashboard",
  },
  ACCOUNTMANAGE: {
    ADD: "transaction/add",
    LIST: "transaction",
    GET: (transactionId) => `transaction/${transactionId}`,
    EDIT: (transactionId) => `transaction/${transactionId}`,
    DELETE: (transactionId) => `transaction/${transactionId}`,
    DASHBOARD: "transaction/dashboard",
  },
};
